### ISSUE TITLE
ImportError: no module named pyautogui

### ISSUE THREAD

**Issue by bucky313** [eClarity/skill-autogui#7]
I installed all the dependencies but i still get 

 ~958 - mycroft.skills.core:load_skill:106 - INFO - ATTEMPTING TO LOAD SKILL: skill-autogui with ID -6433523013532099016
11:15:41.033 - mycroft.skills.core:load_skill:143 - ERROR - Failed to load skill: skill-autogui
Traceback (most recent call last):
File "/home/dustin/mycroft-core/mycroft/skills/core.py", line 111, in load_skill
skill_descriptor["name"] + MainModule, *skill_descriptor["info"])
File "/opt/mycroft/skills/skill-autogui/__init__.py", line 23, in <module>
import pyautogui
ImportError: No module named pyautogui

any help would be amazing.

**Comment by PeskyPotato** [comment]
You may have installed dependencies for Python 2. Try typing `pip --version` if it says version 3, type `pip install pyautogui`. If it is not version 3, try `pip3 install pyautogui`.

**Comment by moabdali** [comment]
I know this is old, but since I just had this problem, maybe someone else might, too:

1)  Make sure you're running the same python version (2.7 vs 3.8 in the year 2020).

2)  Make sure you're running 32 bit regardless of which version you're running in the previous step.  I was running 3.8 64 bit and that's why I couldn't use it.

**Comment by Leontking** [comment]
Close this issue

**Comment by Leontking** [comment]
BRO THIS ISSUE IS 2 YEARS AGO

**Comment by bucky313** [comment]
correct. It is. Hence why I haven't looked on here since then. Nothing posted helped. I had to start the virtual environment within my VM which allowed it to work correctly.
